# This is a basic workflow to help you get started with Actions
name: Sitespeed.io

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # SITESPEED_IO_ARGS: '--config sitespeed.config.js'
  SITESPEED_IO_ARGS: '--speedIndex --performance budget.json'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: create artifacts directory
        run: |
          mkdir artifacts

      # Install NodeJS
      - name: install node
        uses: actions/checkout@v3
        with:
          node-version: '17.x'
 
      # Install Google Chrome
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
      - name: install chrome
        run: |
          chrome --version
          whereis google-chrome
      
      # Install Sitespeed
      - name: install sitespeed
        run: |
          npm install --save-dev sitespeed.io

      - name: Run Sitespeed.io
        run: |
          npx sitespeed.io https://www.visible.com/

# Publish Report
      - name: publish report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: sitespeed-reports
          path: sitespeed-result